FEEDS = [
    {"name": "Associated Press", "url": "https://feeds.apnews.com/apnews/topnews"},
    {"name": "Reuters", "url": "https://feeds.reuters.com/reuters/topNews"},
    {"name": "BBC World News", "url": "http://feeds.bbci.co.uk/news/rss.xml"},
    {"name": "NPR", "url": "https://feeds.npr.org/1001/rss.xml"},
    {"name": "The Guardian", "url": "https://www.theguardian.com/world/rss"},
    {"name": "New York Times", "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"},
    {"name": "Washington Post", "url": "https://feeds.washingtonpost.com/rss/world"},
    {"name": "Politico", "url": "https://www.politico.com/rss/politicopicks.xml"},
    {"name": "Wall Street Journal", "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml"},
    {"name": "Financial Times", "url": "https://www.ft.com/?format=rss"},
    {"name": "Bloomberg", "url": "https://feeds.bloomberg.com/markets/news.rss"},
    {"name": "The Verge", "url": "https://www.theverge.com/rss/index.xml"},
    {"name": "Ars Technica", "url": "http://feeds.arstechnica.com/arstechnica/index"},
    {"name": "Wired", "url": "https://www.wired.com/feed/rss"},
    {"name": "Philadelphia Inquirer", "url": "https://www.inquirer.com/arcio/rss/"},
    {"name": "WHYY", "url": "https://whyy.org/feed/"},
    {"name": "Science News", "url": "https://www.sciencenews.org/feed"},
    {"name": "Stat News", "url": "https://www.statnews.com/feed/"},
    {"name": "ESPN", "url": "https://www.espn.com/espn/rss/news"},
    {"name": "The Atlantic", "url": "https://www.theatlantic.com/feed/all/"},
]
